# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('ip_address', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField()),
                ('ip_address', models.CharField(max_length=15)),
            ],
        ),
    ]
